// lib/registries.ts
// Locked registries: ENG001–ENG120, UI01–UI50 and MC01–MC12.

import type {
  EngineRegistryEntry,
  UIModuleRegistryEntry,
  MapCardRegistryEntry,
} from "./types";

export const ENGINE_CARD_REGISTRY: EngineRegistryEntry[] = [
  { id: "ENG001", displayName: "ENG001", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG002", displayName: "ENG002", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG003", displayName: "ENG003", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG004", displayName: "ENG004", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG005", displayName: "ENG005", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG006", displayName: "ENG006", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG007", displayName: "ENG007", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG008", displayName: "ENG008", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG009", displayName: "ENG009", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG010", displayName: "ENG010", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG011", displayName: "ENG011", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG012", displayName: "ENG012", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG013", displayName: "ENG013", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG014", displayName: "ENG014", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG015", displayName: "ENG015", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG016", displayName: "ENG016", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG017", displayName: "ENG017", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG018", displayName: "ENG018", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG019", displayName: "ENG019", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG020", displayName: "ENG020", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG021", displayName: "ENG021", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG022", displayName: "ENG022", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG023", displayName: "ENG023", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG024", displayName: "ENG024", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG025", displayName: "ENG025", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG026", displayName: "ENG026", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG027", displayName: "ENG027", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG028", displayName: "ENG028", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG029", displayName: "ENG029", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG030", displayName: "ENG030", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG031", displayName: "ENG031", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG032", displayName: "ENG032", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG033", displayName: "ENG033", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG034", displayName: "ENG034", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG035", displayName: "ENG035", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG036", displayName: "ENG036", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG037", displayName: "ENG037", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG038", displayName: "ENG038", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG039", displayName: "ENG039", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG040", displayName: "ENG040", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG041", displayName: "ENG041", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG042", displayName: "ENG042", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG043", displayName: "ENG043", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG044", displayName: "ENG044", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG045", displayName: "ENG045", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG046", displayName: "ENG046", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG047", displayName: "ENG047", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG048", displayName: "ENG048", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG049", displayName: "ENG049", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG050", displayName: "ENG050", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG051", displayName: "ENG051", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG052", displayName: "ENG052", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG053", displayName: "ENG053", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG054", displayName: "ENG054", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG055", displayName: "ENG055", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG056", displayName: "ENG056", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG057", displayName: "ENG057", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG058", displayName: "ENG058", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG059", displayName: "ENG059", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG060", displayName: "ENG060", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG061", displayName: "ENG061", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG062", displayName: "ENG062", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG063", displayName: "ENG063", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG064", displayName: "ENG064", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG065", displayName: "ENG065", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG066", displayName: "ENG066", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG067", displayName: "ENG067", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG068", displayName: "ENG068", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG069", displayName: "ENG069", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG070", displayName: "ENG070", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG071", displayName: "ENG071", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG072", displayName: "ENG072", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG073", displayName: "ENG073", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG074", displayName: "ENG074", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG075", displayName: "ENG075", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG076", displayName: "ENG076", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG077", displayName: "ENG077", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG078", displayName: "ENG078", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG079", displayName: "ENG079", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG080", displayName: "ENG080", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG081", displayName: "ENG081", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG082", displayName: "ENG082", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG083", displayName: "ENG083", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG084", displayName: "ENG084", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG085", displayName: "ENG085", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG086", displayName: "ENG086", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG087", displayName: "ENG087", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG088", displayName: "ENG088", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG089", displayName: "ENG089", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG090", displayName: "ENG090", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG091", displayName: "ENG091", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG092", displayName: "ENG092", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG093", displayName: "ENG093", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG094", displayName: "ENG094", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG095", displayName: "ENG095", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG096", displayName: "ENG096", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG097", displayName: "ENG097", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG098", displayName: "ENG098", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG099", displayName: "ENG099", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG100", displayName: "ENG100", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG101", displayName: "ENG101", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG102", displayName: "ENG102", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG103", displayName: "ENG103", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG104", displayName: "ENG104", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG105", displayName: "ENG105", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG106", displayName: "ENG106", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG107", displayName: "ENG107", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG108", displayName: "ENG108", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG109", displayName: "ENG109", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG110", displayName: "ENG110", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG111", displayName: "ENG111", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG112", displayName: "ENG112", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG113", displayName: "ENG113", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG114", displayName: "ENG114", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG115", displayName: "ENG115", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG116", displayName: "ENG116", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG117", displayName: "ENG117", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG118", displayName: "ENG118", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG119", displayName: "ENG119", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
  { id: "ENG120", displayName: "ENG120", titleStatus: "PENDING_OFFICIAL_TITLE", connectionStatus: "NOT_CONNECTED", calculationStatus: "NOT_YET_COMPUTED", releaseState: "draft" },
];

export const UI_MODULE_REGISTRY: UIModuleRegistryEntry[] = [
  { id: "UI01", displayName: "UI01", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI02", displayName: "UI02", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI03", displayName: "UI03", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI04", displayName: "UI04", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI05", displayName: "UI05", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI06", displayName: "UI06", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI07", displayName: "UI07", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI08", displayName: "UI08", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI09", displayName: "UI09", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI10", displayName: "UI10", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI11", displayName: "UI11", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI12", displayName: "UI12", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI13", displayName: "UI13", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI14", displayName: "UI14", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI15", displayName: "UI15", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI16", displayName: "UI16", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI17", displayName: "UI17", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI18", displayName: "UI18", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI19", displayName: "UI19", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI20", displayName: "UI20", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI21", displayName: "UI21", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI22", displayName: "UI22", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI23", displayName: "UI23", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI24", displayName: "UI24", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI25", displayName: "UI25", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI26", displayName: "UI26", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI27", displayName: "UI27", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI28", displayName: "UI28", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI29", displayName: "UI29", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI30", displayName: "UI30", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI31", displayName: "UI31", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI32", displayName: "UI32", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI33", displayName: "UI33", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI34", displayName: "UI34", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI35", displayName: "UI35", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI36", displayName: "UI36", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI37", displayName: "UI37", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI38", displayName: "UI38", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI39", displayName: "UI39", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI40", displayName: "UI40", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI41", displayName: "UI41", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI42", displayName: "UI42", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI43", displayName: "UI43", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI44", displayName: "UI44", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI45", displayName: "UI45", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI46", displayName: "UI46", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI47", displayName: "UI47", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI48", displayName: "UI48", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI49", displayName: "UI49", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
  { id: "UI50", displayName: "UI50", mappingStatus: "PENDING_OFFICIAL_MAPPING", decisionAuthority: false, releaseState: "draft" },
];

export const MAP_CARD_REGISTRY: MapCardRegistryEntry[] = [
  { id: "MC01", displayName: "Map Answer", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC02", displayName: "Selected Connection", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC03", displayName: "Route Intelligence", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC04", displayName: "Node Intelligence", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC05", displayName: "Ecosystem Context", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC06", displayName: "Territory and Coverage", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC07", displayName: "Data Condition", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC08", displayName: "Evidence and Lineage", category: "CORE", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC09", displayName: "Compatibility", category: "CONDITIONAL", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC10", displayName: "Capacity and Availability", category: "CONDITIONAL", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC11", displayName: "Alternatives", category: "CONDITIONAL", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
  { id: "MC12", displayName: "Dependency and Support", category: "CONDITIONAL", decisionAuthority: false, connectionStatus: "NOT_CONNECTED", releaseState: "draft" },
];

export function getEngineCard(id: string): EngineRegistryEntry | undefined {
  return ENGINE_CARD_REGISTRY.find((card) => card.id === id);
}

export function getUIModule(id: string): UIModuleRegistryEntry | undefined {
  return UI_MODULE_REGISTRY.find((module) => module.id === id);
}

export function getMapCard(id: string): MapCardRegistryEntry | undefined {
  return MAP_CARD_REGISTRY.find((card) => card.id === id);
}
